# Generated by Django 5.0.1 on 2025-07-11 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Vehicle manufacturer (e.g., Toyota, Honda)', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Corolla, Civic)', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year')),
                ('plate', models.CharField(help_text='Vehicle license plate number', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='License plate must contain only letters, numbers, spaces, and hyphens', regex='^[A-Z0-9\\s\\-]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'plate')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Booking start date and time')),
                ('end_date', models.DateTimeField(help_text='Booking end date and time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='backend.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
